#!/usr/bin/env bash
set -euo pipefail

DOMAIN="twaslabel.ru"
WWW="www.twaslabel.ru"
EMAIL="makarenkoae16@gmail.com"
UPSTREAM="127.0.0.1:5000"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash /home/dolepp/label/setup_cloudflare_site.sh" >&2
  exit 1
fi

apt-get update
apt-get install -y nginx certbot python3-certbot-nginx curl

# Make sure the app service is running.
systemctl enable --now label-site

# Get/expand origin certificate for apex + www.
# Stops nginx briefly so certbot standalone can pass even if nginx config does not yet know www.
systemctl stop nginx || true
certbot certonly --standalone \
  --non-interactive --agree-tos --expand \
  -m "$EMAIL" \
  -d "$DOMAIN" -d "$WWW"
systemctl start nginx

# Trust Cloudflare client IP headers.
{
  echo '# Cloudflare real visitor IPs. Generated by setup_cloudflare_site.sh'
  curl -fsSL https://www.cloudflare.com/ips-v4 | sed 's/^/set_real_ip_from /; s/$/;/'
  curl -fsSL https://www.cloudflare.com/ips-v6 | sed 's/^/set_real_ip_from /; s/$/;/'
  echo 'real_ip_header CF-Connecting-IP;'
} > /etc/nginx/conf.d/cloudflare-real-ip.conf

cp -a /etc/nginx/sites-available/${DOMAIN} /etc/nginx/sites-available/${DOMAIN}.bak.$(date +%Y%m%d-%H%M%S) 2>/dev/null || true
cat > /etc/nginx/sites-available/${DOMAIN} <<EOF
server {
    listen 80;
    server_name ${DOMAIN} ${WWW};
    return 301 https://${DOMAIN}\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${WWW};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://${DOMAIN}\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    client_max_body_size 500M;

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$realip_remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header CF-Connecting-IP \$http_cf_connecting_ip;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
EOF

ln -sf /etc/nginx/sites-available/${DOMAIN} /etc/nginx/sites-enabled/${DOMAIN}
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx
systemctl reload-or-restart label-site

echo 'Done. Check:'
echo "curl -I https://${DOMAIN}"
echo "curl -I https://${WWW}"
