"""Application configuration loaded from environment variables."""
import os

try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass


BOT_TOKEN = os.getenv("BOT_TOKEN", "6285811276:AAHoVTSOok-_Bwxe1GWSSSsN7LiP5CynYas")
BOT_USERNAME = os.getenv("BOT_USERNAME", "twaslabel_bot")
WEB_APP_URL = os.getenv("WEB_APP_URL", "https://twas.webhop.me")
CHANNEL_USERNAME = os.getenv("CHANNEL_USERNAME", "@twaslabel")
OWNER_USERNAME = os.getenv("OWNER_USERNAME", "@realjustci")
MANAGER_USERNAME = os.getenv("MANAGER_USERNAME", "@twaslabelmn")
SUPPORT_HOURS = os.getenv("SUPPORT_HOURS", "10:00-22:00 МСК")
ENABLE_MODULAR_REVIEWS = os.getenv("ENABLE_MODULAR_REVIEWS") == "1"
ENABLE_MODULAR_PROFILE = os.getenv("ENABLE_MODULAR_PROFILE") == "1"
ENABLE_MODULAR_SUPPORT = os.getenv("ENABLE_MODULAR_SUPPORT") == "1"
ENABLE_MODULAR_REPORTS = os.getenv("ENABLE_MODULAR_REPORTS") == "1"
ENABLE_MODULAR_CONTRACTS = os.getenv("ENABLE_MODULAR_CONTRACTS") == "1"
ENABLE_MODULAR_ORDERS = os.getenv("ENABLE_MODULAR_ORDERS") == "1"
ENABLE_MODULAR_DRAFTS = os.getenv("ENABLE_MODULAR_DRAFTS") == "1"
ENABLE_MODULAR_PROMOS = os.getenv("ENABLE_MODULAR_PROMOS") == "1"
ENABLE_MODULAR_FINANCE = os.getenv("ENABLE_MODULAR_FINANCE") == "1"
ENABLE_MODULAR_REFERRALS = os.getenv("ENABLE_MODULAR_REFERRALS") == "1"
ENABLE_MODULAR_RELEASE_DETAILS = os.getenv("ENABLE_MODULAR_RELEASE_DETAILS") == "1"
ENABLE_MODULAR_RELEASE_EDIT_MENU = os.getenv("ENABLE_MODULAR_RELEASE_EDIT_MENU") == "1"
ENABLE_MODULAR_RELEASE_LINKS = os.getenv("ENABLE_MODULAR_RELEASE_LINKS") == "1"
ENABLE_MODULAR_RELEASES = os.getenv("ENABLE_MODULAR_RELEASES") == "1"
ENABLE_MODULAR_RELEASE_STATUS_MENU = os.getenv("ENABLE_MODULAR_RELEASE_STATUS_MENU") == "1"
ENABLE_MODULAR_BOOKINGS = os.getenv("ENABLE_MODULAR_BOOKINGS") == "1"
ENABLE_MODULAR_INFO = os.getenv("ENABLE_MODULAR_INFO") == "1"
ENABLE_MODULAR_ADMIN_CONTRACTS = os.getenv("ENABLE_MODULAR_ADMIN_CONTRACTS") == "1"
ENABLE_MODULAR_ADMIN_FINANCE = os.getenv("ENABLE_MODULAR_ADMIN_FINANCE") == "1"
ENABLE_MODULAR_ADMIN_PROMOS = os.getenv("ENABLE_MODULAR_ADMIN_PROMOS") == "1"
ENABLE_MODULAR_ADMIN_RELEASES = os.getenv("ENABLE_MODULAR_ADMIN_RELEASES") == "1"
ENABLE_MODULAR_ADMIN_REPORTS = os.getenv("ENABLE_MODULAR_ADMIN_REPORTS") == "1"
ENABLE_MODULAR_WEB_AUTH = os.getenv("ENABLE_MODULAR_WEB_AUTH") == "1"
ENABLE_MODULAR_DIAGNOSTICS = os.getenv("ENABLE_MODULAR_DIAGNOSTICS") == "1"
ENABLE_MODULAR_TOPUPS = os.getenv("ENABLE_MODULAR_TOPUPS") == "1"
ENABLE_MODULAR_ADMIN_STATS = os.getenv("ENABLE_MODULAR_ADMIN_STATS") == "1"
ENABLE_MODULAR_ADMIN_MENU = os.getenv("ENABLE_MODULAR_ADMIN_MENU") == "1"
ENABLE_MODULAR_ADMIN_SERVICES = os.getenv("ENABLE_MODULAR_ADMIN_SERVICES") == "1"
ENABLE_MODULAR_ADMIN_USERS = os.getenv("ENABLE_MODULAR_ADMIN_USERS") == "1"
ENABLE_MODULAR_ADMIN_USER_INFO = os.getenv("ENABLE_MODULAR_ADMIN_USER_INFO") == "1"
ENABLE_MODULAR_ADMIN_USER_REPORTS = os.getenv("ENABLE_MODULAR_ADMIN_USER_REPORTS") == "1"
ENABLE_MODULAR_ADMIN_USER_RELEASES = os.getenv("ENABLE_MODULAR_ADMIN_USER_RELEASES") == "1"
ENABLE_MODULAR_ADMIN_USER_ROLES = os.getenv("ENABLE_MODULAR_ADMIN_USER_ROLES") == "1"
ENABLE_MODULAR_COMMON = os.getenv("ENABLE_MODULAR_COMMON") == "1"

DB_CONFIG = {
    "dbname": os.getenv("DB_NAME", "postgres"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", "60606611125"),
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5432"),
}

SERVICE_PRICES = {
    "cover": 500,
    "motion": 800,
    "videoshot": 1000,
    "distribution": 1299,
}

ADMIN_IDS = [664506846, 1429461076, 598604529, 1043989654]
PERMANENT_ADMINS = [464793425, 1398275867]
